version: "3"

services:
  postgres-django:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    container_name: postgres-django
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - python-django-app

  web-django:
    build: .
    depends_on:
      - postgres-django
    container_name: python-app-django-web
    working_dir: /var/app/djangoapp
    environment:
        STAGE_TYPE: ${ENV_TYPE}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_TABLE_PREFIX: ${POSTGRES_TABLE_PREFIX}
        POSTGRES_DB_PERSIST: ${POSTGRES_DB_PERSIST}
        POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
        POSTGRES_DB_SOCKET: ${POSTGRES_DB_SOCKET}
        POSTGRES_DB_COLLATION: ${POSTGRES_DB_COLLATION}
#        WWW_ROOT: ${WWW_ROOT}
    volumes:
      - ./:/var/app
    ports:
      - "8000:8000"
    networks:
      - python-django-app

volumes:
  db-data:

networks:
  python-django-app:
    driver: bridge